meta_product_name: "Scoobie"
meta_title: "Scoobie - Search dogs, find friends!"
meta_description: "Scoobie is the first app that connect you with others dog owners. Find the partner for our four-legged friend in a simple and fun way!"
meta_image: "scoobylogo.png"
